#ifdef CREW_VEHICLE
#undef CREW_VEHICLE
#endif
#define CREW_VEHICLE DOUBLES(SIDE,Rifleman)

@VehicleAssign(QPCLASS\(SIDE_FACTION\),SIDE_NUMBER,class CLASS2\(SIDE\,%\))

@Vehicle(BTR,Loyalist,CREW_VEHICLE)
@Vehicle(BTR_SPG,Loyalist,CREW_VEHICLE)
@Vehicle(Ram_MMG,AAF,CREW_VEHICLE)
@Vehicle(Ram_RCWS,AAF,CREW_VEHICLE)
@Vehicle(Ram_MRL,AAF,CREW_VEHICLE)
@Vehicle(Ram_AA,AAF,CREW_VEHICLE)
@Vehicle(Ram_AT,AAF,CREW_VEHICLE)
@Vehicle(LUT_Ammo,Indep,CREW_VEHICLE)
@Vehicle(LUT_MRL,Indep,CREW_VEHICLE)
