private _events = [
    "OnBeforeMissionPreview",
    "OnConnectingStart",
    "OnConnectingEnd",
    "OnCopy",
    "OnCut",
    "OnDeleteUnits",
    "OnEntityMenu",
    "OnGridChange",
    "OnHistoryChange",
    "OnMapClosed",
    "OnMapOpened",
    "OnMessage",
    "OnMissionAutosave",
    "OnMissionExportSP",
    "OnMissionExportMP",
    "OnMissionListChange",
    "OnMissionLoad",
    "OnMissionNew",
    "OnMissionPreview",
    "OnMissionPreviewEnd",
    "OnMissionSave",
    "OnMissionSaveAs",
    "OnModeChange",
    "OnMoveGridDecrease",
    "OnMoveGridIncrease",
    "OnMoveGridToggle",
    "OnPaste",
    "OnPasteUnitOrig",
    "OnRedo",
    "OnRotateGridDecrease",
    "OnRotateGridIncrease",
    "OnRotateGridToggle",
    "OnScaleGridToggle",
    "OnSearchCreate",
    "OnSearchEdit",
    "OnSelectionChange",
    "OnServerToggle",
    "OnSubmodeChange",
    "OnSurfaceSnapToggle",
    "OnTerrainNew",
    "OnToggleMapIDs",
    "OnToggleMapTextures",
    "OnTogglePlaceEmptyVehicle",
    "OnUndo",
    "OnVerticalToggle",
    "OnWidgetArea",
    "OnWidgetNone",
    "OnWidgetRotation",
    "OnWidgetScale",
    "OnWidgetToggle",
    "OnWidgetTranslation",
    "OnWorkspacePartSwitch"
];

{
    call compile format ["add3DENEventHandler [""%1"", {
        systemChat format [""3DEN Event: %1, Args: %%1"", _this];
    }];", _x];
} forEach _events;
