@Facewear({
  "G_Balaclava_oli" : 1,
  "G_Balaclava_oli_lxWS" : 1,
  "G_Shemag_oli" : 1,
  "G_Shemag_shades" : 1,
  "G_Shemag_tactical" : 1,
  "G_Bandanna_khk" : 1,
  "G_Bandanna_oli" : 1,
  "G_Headset_lxWS" : 1,
  "G_HeadSetMilitary" : 1,
  "synixe_mgp_f_face_shield_rgr_shemagh_rgr" : 1,
  "synixe_mgp_f_face_shield_rgr_shemagh_rgr_ess" : 1,
  "synixe_mgp_f_face_shield_rgr_shemagh_rgr_shades" : 1,
  "" : 5,
});
