@Headgear({
    "synixe_mgp_h_cap_blk": 1,
    "synixe_mgp_h_cap_blk_earphones": 1,
    "H_Cap_blu": 1,
    "H_Cap_blu_headset": 1,
    "synixe_mgp_h_cap_cb": 1,
    "H_Cap_blk": 1,
    "H_Cap_grn": 1,
    "H_Cap_oli": 1,
    "synixe_mgp_h_cap_rgr": 1,
    "H_Cap_red": 1,
    "H_Cap_tan": 1,
    "H_Headset_light": 1,
    "Aegis_H_MilCap_nohs_blk": 1,
    "H_MilCap_blk": 1,
    "Aegis_H_Milcap_nohs_blue_F": 1,
    "H_MilCap_blue": 1,
    "Atlas_H_MilCap_nohs_sgg": 1,
    "lxWS_H_Headset": 1,
    "": 16,
});
