name = "Synixe Factions"
prefix = "synixe_factions"
mainprefix = "s"

[hemtt.launch.default]
dlc = ["ws", "rf"]
workshop = [
    "3499977893", # ADT
    "factions:@3den_attributes_fast_load",
    "factions:@ace_noactionmenu",
    "factions:@ace_nocrosshair",
    "factions:@ace_particles",
    "factions:@ace_realisticdispersion",
    "factions:@ace_tracers",
    "factions:@ace",
    "factions:@aegis_atlas",
    "factions:@aegis_opposing_forces",
    "factions:@aegis",
    "factions:@cba_a3",
    "factions:@cba_rf",
    "factions:@cba_ws",
    "factions:@generic_civilian_clothing",
    "factions:@gorkas",
    "factions:@jca_m72a7",
    "factions:@jca_mp5a5",
    "factions:@jca_ump45",
    "factions:@low_visibility_attir",
    "factions:@mu",
    "factions:@oteden",
    "factions:@rf",
    "factions:@synixe_armoury",
    "factions:@synixe_contractors",
    "factions:@synixe_mgp",
    "factions:@synixe_standardization",
    "factions:@theseus_services",
    "factions:@toh_characters",
    "factions:@ws",
]
