@Facewear({
    "synixe_mgp_f_face_shield_blk_ess": 1,
    "synixe_mgp_f_face_shield_khk_ess": 1,
    "synixe_mgp_f_face_shield_mc_ess": 1,
    "synixe_mgp_f_face_shield_cb_ess": 1,
    "synixe_mgp_f_face_shield_aor1_ess": 1,
    "synixe_mgp_f_face_shield_rgr_ess": 1,

    "synixe_mgp_f_face_shield_aor1": 1,
    "synixe_mgp_f_face_shield_blk": 1,
    "synixe_mgp_f_face_shield_khk": 1,
    "synixe_mgp_f_face_shield_mc": 1,
    "synixe_mgp_f_face_shield_rgr": 1,
    "synixe_mgp_f_face_shield_cb": 1,

    "synixe_mgp_f_shades": 1,
    "G_Shades_Black": 1,
    "G_Shades_Blue": 1,
    "G_Shades_Green": 1,
    "G_Shades_Red": 1,
    "G_Shades_Yellowred": 1,

    "G_Balaclava_TI_blk_F": 1,
    "G_Balaclava_TI_alt_F": 1,
    "JCA_G_balaclava_01_glasses_black_F": 1,
    "JCA_G_balaclava_01_black_F": 1,
    "JCA_G_balaclava_01_sand_F": 1,
    "JCA_G_balaclava_01_glasses_sand_F": 1,
    "Aegis_G_Condor_EyePro_F": 1,
    "JCA_G_Glasses_Tactical_tinted_black_F": 1,
    "JCA_G_Glasses_Tactical_tinted_olive_F": 1,
    "JCA_G_Glasses_Tactical_tinted_sand_F": 1,
    "": 10,
});
