@Vests({
    "variants" : {
        "V_TacVest_blk": 1,
        "V_TacVest_khk": 1,
        "V_TacVest_oli": 1,
        "V_TacVest_camo": 1,
        "Atlas_Tacvest_Ard_F": 1,
        "V_TacVest_rig_blk_RF": 1,
        "V_TacVest_rig_khk_RF": 1,
        "V_TacVest_rig_oli_RF": 1,
        "V_BandollierB_blk": 1,
        "V_BandollierB_cbr": 1,
        "V_BandollierB_rgr": 1,
        "V_HarnessO_brn": 1,
        "V_HarnessO_whex_F": 1,
        "V_HarnessO_tan": 1,
        "V_lxWS_HarnessO_oli": 1,
        "V_lxWS_TacVestIR_oli": 1,
        "V_HarnessOSpec_brn": 1,
        "V_HarnessOSpec_whex_F": 1,
        "V_HarnessOSpec_tan": 1,
        "V_ChestrigF_blk": 1,
        "V_ChestrigF_rgr": 1,
        "V_ChestrigF_khk": 1,
        "V_ChestrigF_oli": 1,
        "Aegis_V_ChestrigEast_grn_F": 1,
        "Aegis_V_ChestrigEast_khk_F": 1,
        "Aegis_V_ChestrigEast_oli_F": 1,
        "Aegis_V_ChestrigEast_tan_F": 1,
        "V_TacChestrig_cbr_F": 1,
        "V_TacChestrig_grn_F": 1,
        "V_TacChestrig_oli_F": 1,
    },
    "packs": [
        "t4_standard",
        "military_standard"
    ],
});
