name: arma

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Build Mod
        run: hemtt build

      - name: Rename build folder
        run: mv .hemttout/build .hemttout/@synixe_factions

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: synixe_factions.zip
          path: .hemttout/@*
          include-hidden-files: true 
